# permissions for end users to view policyshepherds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policyshepherd-viewer-role
rules:
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policyshepherds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - policy.open-cluster-management.io
  resources:
  - policyshepherds/status
  verbs:
  - get
